use std::sync::Arc;

use columnar::pipeline::Pipeline;
use pyo3::exceptions::PyRuntimeError;
use pyo3::prelude::*;
use columnar::macros::Columnar;
use columnar::buffer::Schema;
use columnar::ring::{ConnectorRx, ConnectorTx, Pool};

const MAX_STR_LEN: usize = 32;
const MAX_ANNOTATIONS_LEN: usize = 10;
const MAX_SCORES_LEN: usize = 4;

pub mod alignment {
    use super::*;

    #[derive(Debug, Clone, Columnar)]
    #[columnar(pyclass = "PyAlignmentBatch")]
    pub struct Alignment {

        /// unique identifier for this alignment
        pub id: u32,

        /// position
        pub occurence: u32,
        pub strand: u8,

        /// row-major byte buffers
        pub rguide: [u8; MAX_STR_LEN],
        pub rseq: [u8; MAX_STR_LEN],

        /// alignment results
        pub mism: u8,
        pub bdna: u8,
        pub brna: u8,

        /// column-major scores
        #[columnar(group)]
        pub score: [f32; MAX_SCORES_LEN],

        /// column-major annotations
        #[columnar(group)]
        pub annotations: [u32; MAX_ANNOTATIONS_LEN]
    }
}

pub mod sequence {
    use super::*;

    #[repr(C)]
    #[derive(Debug, Columnar)]
    #[columnar(pyclass = "PySequenceBatch")]
    pub struct Sequence {
        pub id: u32,
    }
}

// =============================================================================
// Batch wrappers — schema-specific Python-visible batch handles
// =============================================================================

// Auto-generated by #[columnar(pyclass = "...")]
pub use alignment::PyAlignmentBatch;
pub use sequence::PySequenceBatch;

// =============================================================================
// Pipeline factory — wires up stages with Python callbacks
// =============================================================================

#[pyclass(str = "{pipeline:?}")]
pub struct PyPipeline {

    pipeline: Pipeline,
    seq_pool: Arc<Pool<sequence::SequenceSchema>>,

    src_tx: Option<ConnectorTx<sequence::SequenceSchema, ()>>,
    out_rx: Option<ConnectorRx<alignment::AlignmentSchema, ()>>,
}

impl Drop for PyPipeline {
    fn drop(&mut self) {
        // Close channels first so worker threads unblock and exit,
        // then Pipeline::drop can join them without deadlocking.
        self.src_tx.take();
        self.out_rx.take();
    }
}

#[pymethods]
impl PyPipeline {

    // Example submit
    fn submit(&mut self, py: Python<'_>) {
        println!("Submitting new sequence batch...");

        let mut input = self.seq_pool.acquire().unwrap();
        input.as_mut().mutate(
            (sequence::schema::id,),
            |(ids,)| {
                for (i, id) in ids.iter_mut().enumerate() {
                    *id = i as u32;
                }
            }
        );

        // Release GIL so stage threads can acquire it
        py.detach(|| {
            self.src_tx.as_ref().unwrap().send(input).unwrap();
        });

        println!("Submission done!")
    }

    // Example receive
    fn receive(&mut self, py: Python<'_>) -> PyResult<PyAlignmentBatch> {
        println!("Receiving alignment batch...");

        // Release GIL so stage threads can acquire it while we block
        let rx = self.out_rx.as_ref()
            .ok_or(PyRuntimeError::new_err("pipeline already shut down"))?;
        let result = py.detach(|| rx.recv());

        match result {
            Ok(batch) => {
                print!("Received!");
                Ok(PyAlignmentBatch { batch: Some(batch) })
            }
            Err(e) => Err(PyRuntimeError::new_err(format!("recv failed: {e}")))
        }
    }
}

#[pymodule]
mod columnar_python {
    use columnar::{ext::pyo3::PyColumnView, ring::connector};
    use pyo3::prelude::*;
    use crate::*;

    /// Create a pipeline: source (Python) → transform (Python callback on Rust thread) → sink (Python).
    ///
    /// The `transform` callback receives a `PyAlignmentWriteBatch` for in-place modification.
    /// After the callback returns, the batch is auto-published downstream.
    #[pyfunction]
    fn create_pipeline(slots: usize, elements: usize, transform: Py<PyAny>,) -> PyPipeline {

        println!("Size of a single alignment: {} bytes", alignment::AlignmentSchema::LAYOUT.stride);
        let (seq_pool, align_pool) = (
            Arc::new(Pool::<sequence::SequenceSchema>::new(slots, elements)),
            Arc::new(Pool::<alignment::AlignmentSchema>::new(slots, elements))
        );

        let mut pipeline = Pipeline::new();

        let (src_tx, src_rx) = connector::<sequence::SequenceSchema, ()>(2);
        let (out_tx, out_rx) = connector::<alignment::AlignmentSchema, ()>(2);

        // Middle stage: Rust thread receives sequences, produces alignment batches,
        // calls Python callback for in-place transformation, then forwards downstream.
        pipeline.stage("py-transform", src_rx, 1, move |input, _ctx| {
            println!("running py-transform...");

            let result = align_pool.acquire().unwrap();
            let alignments = PyAlignmentBatch { batch: Some(result) };
            let sequences = PySequenceBatch { batch: Some(input) };

            Python::try_attach(|py| {

                let py_input = Py::new(py, sequences).unwrap();
                let py_batch = Py::new(py, alignments).unwrap();

                transform.call1(py, (&py_input, &py_batch,)).unwrap();

                // Take the batch back after callback returns
                let mut inner = py_batch.borrow_mut(py);
                if let Some(batch) = inner.batch.take() {
                    out_tx.send(batch).unwrap();
                }
            });

            println!("run!");
        });

        PyPipeline { pipeline, seq_pool, src_tx: Some(src_tx), out_rx: Some(out_rx) }
    }

    #[pymodule_init]
    fn init(m: &Bound<'_, PyModule>) -> PyResult<()> {
        m.add_class::<PyColumnView>()?;
        m.add_class::<PySequenceBatch>()?;
        m.add_class::<PyAlignmentBatch>()?;
        Ok(())
    }
}
